### PR TITLE
[japscan] updated image detection

### LINKED ISSUE #2049: [Japscan] Small / unusual picture size get the download in error
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
Some manga on japscan don't work each time i try (cancel at the end)

**To Reproduce**
1)Try to download "Air Gear" Volume 8 or Volume 9 for exemple or akane-chan overdrive volume 2
2)Wait for the download to complete
3)It'll crash at the end

**Context (please complete the following information):**
 - OS : Windows10 64 bits
 - HakuNeko Stable and nightly versions, 32bits and 64bits

Seem to be related to the scan picture size.
All the manga with this bug have a very small / unusual picture size in the manga (https://www.japscan.co/lecture-en-ligne/air-gear/volume-8/109.html or https://www.japscan.co/lecture-en-ligne/akane-chan-overdrive/volume-2/4.html for exemple)

Screen Shot 014

Screen Shot 015

### PR DESCRIPTION
**Pull request by 27136773**
Changeset: https://github.com/manga-download/hakuneko-plugins/commit/1295186bcdb7cf4b0858a22f0e68673574647abd
Resolves #2049

### CODE REVIEW

**Review by Sheepux — CHANGES_REQUESTED** [review]
Still issue on Air Gear volume 8

`InterProcessCommunication.mjs:13 Error: Failed to load "https://www.japscan.co/lecture-en-ligne/air-gear/volume-8/109.html" within the given timeout of 60 seconds!
    at Request.mjs:213
  | (anonymous) | @ | InterProcessCommunication.mjs:13
-- | -- | -- | --
  | async function (async) |   |  
  | (anonymous) | @ | InterProcessCommunication.mjs:10
  | emit | @ | events.js:210
  | onMessage | @ | init.ts:51
`

**Comment by 27136773** [comment]
Changeset: https://github.com/manga-download/hakuneko-plugins/commit/6b1d612b32a8c317f768adfe1f20985e6626c031

**Review by Sheepux — APPROVED** [review]
/LGTM

**Comment by satsukiyatoshi** [comment]
Bug here again, for exemple impossible to download alice 19th volume 5 (using lastest nightly):
https://www.japscan.co/lecture-en-ligne/alice-19th/volume-5/100.html

**Pull request merged**
