### PR TITLE
Update MangaKakalot.mjs

### PR DESCRIPTION
**Pull request by Torablue**
Update website's url

### CODE REVIEW

**Comment by MikeZeDev** [comment]
1) https://mangakakalot.com works. They did NOT change domain.

2) You didnt even changed the Regex for clipboard to match the new URL.

I vote to reject this PR, its useless.

**Comment by MikeZeDev** [comment]
I may have sounded harsh, can you elaborate on why you want it changed?

**Comment by Torablue** [comment]
The new one works without vpn for me

**Comment by MikeZeDev** [comment]
> The new one works without vpn for me

We wont change the url to use a clone.  Unfortunately, Its not Hakuneko role to fix someone personal connection issues.
I hope you can understand that.

Maybe you only need to use alternative DNS on your computer to circumvent the blocking? 

Closed.

**Pull request closed without merging**
