### PR TITLE
Oxapk: create connector

### PR DESCRIPTION
**Pull request by TristanWasTaken**
Create connector for https://oxapk.com/

### CODE REVIEW

**Review by MikeZeDev — APPROVED** [review]
Good. Maybe replace file name with Oxapk?

**Comment by TristanWasTaken** [comment]
@MikeZeDev sure, but that naming format doesn't match with the other files?

**Comment by MikeZeDev** [comment]
> @MikeZeDev sure, but that naming format doesn't match with the other files?

Its a misunderstanding. i was talking about MJS filename.

Its **Okapk** class, it should be **Okpak.mjs** , icon name and connector ID must still be lowercase ,

Sorry i wasnt clear enough :/

**Comment by TristanWasTaken** [comment]
ah
yeah I'll change it

**Comment by TristanWasTaken** [comment]
@MikeZeDev done

**Review by MikeZeDev — APPROVED** [review]

**Comment by 27136773** [comment]
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27oxapk%27&type=code)

**Pull request merged**
