### PR TITLE
Website updates/additions

### LINKED ISSUE #3367: [Japanread] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**The download does not work.
download does not work

**To Reproduce**
1. Name of connector : Japanread
2. Name of manga (if connector update is working) : A Way To Protect You, Sweetheart
3. Name of chapter (if manga update is working) : all
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Failed to load resource: the server responded with a status of 404 ()
mjs/engine/Connector.mjs:618 Error: Failed to receive content from "https://www.japanread.cc/api/?type=chapter&id=138242" (status: 404) - 
    at mjs/engine/Connector.mjs:469
    at async JapanRead._getPages (mjs/connectors/JapanRead.mjs:70)
    at async JapanRead._getPageList (mjs/engine/Connector.mjs:615) EventTarget

**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #3426: [GManga] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
today i was going to download (Sweet Home)
from (GManga) but i can't open or download it and it is saying (cannot read property 'textContent' of undefined)

**To Reproduce**
1. GManga
2. Sweet Home
3. Sweet Home all chapters
4. cannot read property 'textContent' of undefined

**HakuNeko (please complete the following information):**
 - Version 6.1.7@845bf9

### LINKED ISSUE #3436: [Feature] Add more hosts to the blacklist (from Japscan)
Just tried Japscan on nightly because someone was saying it doesnt work. 

Its working but i got fucking spammed by ESET antiviruses alerts (165 !) .

I filtered all the addresses, here they are.

https://graveuniversalapologies.com
https://hunchmotherhooddefine.com
https://immunepine.com
https://jigsawthirsty.com
https://mineralscreamrobes.com
https://pianistrefutationgoose.com
https://prowlenthusiasticcongest.com
https://radarconsultation.com
https://sharpconnatechamber.com
https://sweaterwarmly.com
https://utmostsecond.com

Would you consider adding them to HN blacklist? Thanks a lot :)

### LINKED ISSUE #3444: [Mangadex] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
While the frontend on [mangadex.org](https://mangadex.org) is not up yet, the backend and v5 API on [api.mangadex.org](https://api.mangadex.org) is up.

**Describe the bug**
If you are using the old Mangadex API, you can now upgrade to the new one [api.mangadex.org/docs.html](https://api.mangadex.org/docs.html).

**To Reproduce**
1. Select the Mangadex connector
2. Search for any manga

**Screenshots**
Screenshot 2021-05-11 115428

**HakuNeko (please complete the following information):**
 - Version [v6.1.7 and Nightly]

### LINKED ISSUE #3446: [manhuascan.com] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
when i try to download anything from the website it comes up as a red error in a triangle. i've tried a couple different sources, same thing happens

**To Reproduce**
1. Name of connector manhuascan.com
2. Name of manga (if connector update is working) nothing is worknig
3. Name of chapter (if manga update is working) nothing
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #3456: [Site Request] Patatescan
Name of the website
Patatescan

Website urls (examples below)

Site: https://patatescan.com/
Manga List: https://patatescan.com/manga/
Manga example: https://patatescan.com/manga/call-me-the-goddess-of-vengeance/
Chapter online viewer example: https://patatescan.com/call-me-the-goddess-of-vengeance-1/
Languages
French

*Website relationship
None

Additional details
None

### LINKED ISSUE #3457: [Site Request] Japanime
**Name of the website**
Japanime

**Website urls (examples below)**
- Site: https://japanime.ch/
- Manga List: https://japanime.ch/manga/
- Manga example: https://japanime.ch/manga/matchless-emperor/
- Chapter online viewer example: https://japanime.ch/manga/matchless-emperor/chap-1/

**Languages**
French

**Website relationship*
None

**Additional details**
None

### LINKED ISSUE #3465: [Site Request] Hentaimimi
**Name of the website**
Hentaimimi

**Website urls (examples below)**
- Site: https://hentaimimi.com/
- Manga List: I don't found it, sorry
- Manga example: https://hentaimimi.com/view/7653
- Chapter online viewer example: https://hentaimimi.com/view/7653#lg=1&slide=0

**Languages**
English

**Website relationship*

**Additional details**

### PR DESCRIPTION
**Pull request by 27136773**
References: dazedcat19/FMD2#550
References: dazedcat19/FMD2#547
References: dazedcat19/FMD2#544
References: dazedcat19/FMD2#538
References: dazedcat19/FMD2#535
References: dazedcat19/FMD2#534

### CODE REVIEW

**Comment by kannguyen** [comment]
@ronny1982 ManhuaScan has already changed the encrypted function so this pull request won't work.

**Comment by Robonau** [comment]
> @ronny1982 ManhuaScan has already changed the encrypted function so this pull request won't work.

ManhuaScan itself doesn't seem to load any pages, whilst they did change there encryption function the site doesn't even know how to decrypt right now

**Comment by kannguyen** [comment]
> > @ronny1982 ManhuaScan has already changed the encrypted function so this pull request won't work.
> 
> ManhuaScan itself doesn't seem to load any pages, whilst they did change there encryption function the site doesn't even know how to decrypt right now

They are probably hiding the decrypted function by encoding this file:
https://manhuascan.com/app/manga/themes/default/assets/js4/chapter2.js?100

Also, it seems they changed several encrypt methods in the past few days.

**Review by Sheepux — APPROVED** [review]
/LGTM
Some leftover commented imports in Mangadex but i guess it will be soon reworked again.
Could use some more "positive attitude" in the console.error ;-)

**Pull request merged**
