### PR TITLE
Fix Mangalek : change domain

### PR DESCRIPTION
**Pull request by Ali-932**
Changed Mangalek domain to a working domain

### CODE REVIEW

**Comment by MikeZeDev** [comment]
I've just literally approved a request for it, but with another url. You see the problem now , @PD-ZIRO ?

https://github.com/manga-download/hakuneko/pull/6910

**Comment by PD-ZIRO** [comment]
> I've just literally approved a request for it, but with another url. You see the problem now , @PD-ZIRO ?
> 
> #6910

Yes, I understand the problem now، This man is like the rest of them. The most important thing to them is that the site works. They do not care about the domain. The most important thing is that the domain works

**Comment by Ali-932** [comment]
> > I've just literally approved a request for it, but with another url. You see the problem now , @PD-ZIRO ?
> > 
> > #6910
> 
> Yes, I understand the problem now، This man is like the rest of them. The most important thing to them is that the site works. They do not care about the domain. The most important thing is that the domain works

Why are you guys so aggressive? It's a working domin just the like rest of the other 3

**Comment by PD-ZIRO** [comment]
> > > I've just literally approved a request for it, but with another url. You see the problem now , @PD-ZIRO ?
> > > #6910
> > 
> > 
> > Yes, I understand the problem now، This man is like the rest of them. The most important thing to them is that the site works. They do not care about the domain. The most important thing is that the domain works
> 
> Why are you guys so aggressive? It's a working domin just the like rest of the other 3

No problem, my friend. The domain has been changed to: lekmanga.net domain works Enjoy your time ^^

**Comment by MikeZeDev** [comment]
No you dont get it. Everyone just think his own mangalek domain is the good one when i swear no one knows.
I just approved yours because that way its the same than main Mihon  extensions repo, consider yourself lucky.

See you in a week or so, when this one will be dead again, for another rodeo. :D

**Pull request closed without merging**
