### PR TITLE
Updated keyboard shortcuts in reader

### PR DESCRIPTION
**Pull request by guydht**
- Changed key recognition to be by code instead of by key
- Swiitched page up/down and arrow up/down
- Made the arrow up/down (previously page up/down) event be smooth

### CODE REVIEW

**Comment by 27136773** [comment]
I think changes should be applied to both, light theme and dark theme.
Is the key code reliable for different keyboard locales?
e.g. US keyboard uses the same key for `+` and `=`, so the key code for `=` will work, but on other locales the `=` sign may not be on the same key as the `+`

**Review by Sheepux — CHANGES_REQUESTED** [review]
You should not use smooth scrolling on "simple move down" as it locks repeating scrolling (everytime you press the key the velocity restarts and during my testing it felt weird/wrong).
You should let it to the default behavior even though it's not smooth :  this.$.container.scrollTop -= 64;

**Comment by Sheepux** [comment]
Regarding the swap of up/down & page/up i'm ok to get it back to what we expect from a default browser behavior. 
I'll have to work on being able to change keys settings in the config menu (we expected a key behavior war).

**Review by Sheepux — CHANGES_REQUESTED** [review]
As Ronny mentioned, changes should also be done in the light theme (currently 2 themes to maintain, that will maybe change "soon")

**Comment by guydht** [comment]
I'm not 100% happy with the "scrollsmoothly" function but it gets the job done (doesn't feel weird when spamming the arrow keys).
I changed the minus/plus handling because I really don't know if there are locales that behave differently and better safe than sorry.
Aaaaand forgot that light theme exists :/

**Comment by Sheepux** [comment]
The "tiny scroll" function seems to be working nicely (i've tested your branch).
I'm glad someone is also working on improving the reader 👍

**Review by Sheepux — APPROVED** [review]
Looks Good To Me

**Pull request merged**
