### PR TITLE
[9anime] fixed page delay protection + WAF captcha, support MP4 stream from Vidstream mirror

### LINKED ISSUE #2809: [Feature] Video Stream Selection
**Is your feature request related to a problem? Please describe.**
Improve video stream selection by prioritizing format type and source

**Describe the solution you'd like**
Priorize streams instead of using the last stream
1. Format ➔ `.mp4` > `.m3u8`
2. Source ➔ `google.com` > anything else
3. Use first stream instead of last

**Context (please complete the following information):**
See: https://github.com/manga-download/hakuneko/blob/bfee7368fd6cfaeb3eafa8a1166a67be7896b374/src/web/mjs/videostreams/MyCloud.mjs#L18

**Additional context**
Multi-Stream Sample for `Vidstream` engine from 9anime (Dr. Stone - Episode 001):
https://cdn.discordapp.com/attachments/581629183159959584/791283567795372032/unknown.png

### PR DESCRIPTION
**Pull request by 27136773**
- [x] Maybe captcha check could be moved to the captcha check script for `fetchUI` in `Request.js`?

### CODE REVIEW

**Comment by ronny1982** [comment]
TODO: MAybe captcha check could be moved to the captcha check script for `fetchUI` in `Request.js`?

**Comment by Sheepux** [comment]
Unable to get the connector working for any manga (using default config).
Test on "Obsolete", getting 404 on Vidstream & MyCloud. Works fine on StreamTape.
Works fine for all within HN browser.

`DownloadJob.mjs:168 GET https://exnog.vidstream.pro/LVN1aauBvSd2LCIpKTpIdPDjklw5+15fV9yrZWO4nKvbSnBclqc0f59CNA+c9nDqR6zNKkekO+7FuBiooZtYlGu90pxMY5TuL8m77SeZxaDSqX6jvEinYyM94Cbct91RorFGyD1zXs8b4wQcqLz7MzhxaE2LxnfsWo05EPXGZheVAnif8EXdTPIN5fAK4lYb/v/hls/720/720.m3u8 404
DownloadJob.mjs:168 GET https://kljyq.mcloud2.to/ae2979a9766984d81c927d4e3835a26cd49974f2b6fbef010176c51dd57cfb37cfd66c620666ef51223135dc6fbf98f04539c61268f30753a5db5b2af3adb5b2bb39af77053e1ac2e57710b26b340d82b1dc9fe69a7cb77d33559a199ee905de0f804433beea5ffd172a0e5ccc51a9631fd63792e32de12b6b73548dcd57d761/m/hls/720/720.m3u8 404`

**Comment by 27136773** [comment]
Maybe the Videostream Throttle needs to be increased in settings for 9anime.
When downloading to many packets / minute, it will block requests for a while.

I also figured out the new captcha location and added it (show user the window in case of captcha...).

----

image

**Comment by Sheepux** [comment]
DL still not working while the video can been see within HN browser without any action.
404 seems to appear before the video download (increased throtling to 5000ms)
Enclosed har & network tab
[9anime_vidstream.har.txt](https://github.com/manga-download/hakuneko/files/5862208/9anime_vidstream.har.txt)

**Comment by 27136773** [comment]
I cannot reproduce the problem and therefore fix it.
Since 9anime isn't working right now i suggest to merge the changes anyway, so hopefully the majority of users can use it again.
Further problem may be tracked in additional tickets.

**Review by Sheepux — APPROVED** [review]

**Pull request merged**
