### PR TITLE
[comikey] fixed image extraction

### LINKED ISSUE #4136: [Comikey] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Downloading any free chapter doesnt work. Keeps throwing error.

**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by 27136773**
Review:
- manga-download/hakuneko-plugins@41cebed
- manga-download/hakuneko-plugins@a40ca95
- manga-download/hakuneko-plugins@6c5aa32

### CODE REVIEW

**Comment by amit34521** [comment]
The highest quality returned happens to be webp. however, can you make it to consider the alternate array only when the default readingorder.href is missing as in the image below?

image

**Comment by 27136773** [comment]
> The highest quality returned happens to be webp. however, can you make it to consider the alternate array only when the default readingorder.href is missing as in the image below?
> 
> image

What manga/chapter is this?
From my findings the default image is always part of the alternate links as well, in which case only the sorting needs to be changed (consider `.jpg` < `.webp` besides the highest resolution)

**Comment by amit34521** [comment]
I checked both "battle in 5 seconds" ch 80 & 81 and "happy harem making" ch 60 manga. In both of them, I noticed that the highest jpeg was not the part of the alternate array. 
The image is from happy harem making ch 61.

Looking at it, they are providing the jpeg in the root and rest options in the alternate array.

**Review by Sheepux — APPROVED** [review]
/LGTM

A quite fun way to handle the case. (such "wars" are actually the fun ones)

**Pull request merged**
