### PR TITLE
Feature/new thing

### PR DESCRIPTION
**Pull request by Xsamename**
-Add connector for worldmanhwas
-Add new content indicator for bookmarked mangas
-Add options to make build win portable 64 easier
-Remove duplication of html theme files

Note:
I may not have time to fix/recode this PR. You can reject it or someone can continue to improve it

### CODE REVIEW

**Comment by MikeZeDev** [comment]
If i were you i would put the website addition in a separate PR. Thats a big PR Ronny is busy but we at least could validate the website separately. Btw you didnt add icon for the website (unless i missed it)

**Comment by Sheepux** [comment]
I'd suggest to contribute to HaruNeko (next version) https://github.com/manga-download/haruneko

**Comment by MikeZeDev** [comment]
> I'd suggest to contribute to HaruNeko (next version) https://github.com/manga-download/haruneko

Should we only allow PR and Issues for bug fixing ? This would void a crapload of work i did tho.

**Comment by Sheepux** [comment]
Nah it's ok as haru will take some time before being release, it's just that review won't have priorities

**Comment by 27136773** [comment]
Since HakuNeko is reaching its end-of-life cycle, I vote for not to merge complex PRs that poses a risk to introduce bugs.

**Comment by MikeZeDev** [comment]
For the reasons stated above, i am closing this. Thanks for your contribution anyway. Feel free to resubmit the website in a separate PR i'll gladly look into it quickly.

Dear colleagues feel free to reopen it if you want ;)

**Pull request closed without merging**
