### PR TITLE
Change domain of AnimePahe

### LINKED ISSUE #7001: [AnimePahe] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
I tried downloading anime from animepahe, but it errors saying [Referenceerror: hls is not defined]. I tried with other sites, same problem as well. I tried to download manga/manhwa chapters, it works well. Only with anime becomes error.

**Expected behavior**
I want to download anime again, with no errors.

**Screenshots**
image

**Context (please complete the following information):**
 - OS: Windows10
 - HakuNeko Version 6.1.7
Screenshot 2024-04-21 202530

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/7001

### CODE REVIEW

**Review by heyaclizun — COMMENTED** [review]
I still cannot download. How to do it? 
image

**Review by heyaclizun — APPROVED** [review]
I approve this change. I want to download as soon as I can.

**Comment by MikeZeDev** [comment]
Its pointless. It has to be approved by a fellow maintainer.

**Comment by MikeZeDev** [comment]
image
image

I told you all you need to do. Use nightly and wait.

**Review by 27136773 — APPROVED** [review]

**Comment by heyaclizun** [comment]
Hello, now that it has been resolved, but there are no episodes or chapters to load. What will I do?
image

**Comment by MikeZeDev** [comment]
1) Dont ask non-dev related questions on PR
2) Use nightly.

**Pull request merged**
