### PR TITLE
Website Maintenance

### LINKED ISSUE #3801: [Manhwaland.me] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Don´t load any manga of this conector.

**To Reproduce**
1. Manhwaland (to replace site https://manhwaland.me/)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
gambar

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #3803: [sekaikomik.in] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Don´t load any manga of this conector. can't update the manga list

**To Reproduce**
1. https://www.sekaikomik.in/ (to replace site https://www.sekaikomik.in/)

**Screenshots**
gambar

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### LINKED ISSUE #3825: [Lovehug] Connector not working : change in website domain
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

Description:
The domain of lovehug main website has been changed from **Lovehug.net** to **beta.lovehug.net**

### LINKED ISSUE #3839: [GANMA!] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Connector work, loading the manga list of said website, but is not loading any of the chapters list of any serie, whatever serie you click on

**To Reproduce**
1. GANMA!
2. Any manga that is updated, some of the recently updated クズ浪人生、人生が辛いので夜のお姉さんを呼んでみた
3. No Chapter List Load, unless is a bookmarked manga and have downloaded chapters, but no new chapters show up
4. Long error, if if s a bookmarked manga it don't let you download chapters "No Available Action", in the F12 console 
5. Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://ganma.jp/api/2.0/magazines/57ec9f50-a9b2-11eb-ab66-3e4b7649bbaa" (status: 404) - 
    at Connector.mjs:469 , similar error for any other manga 

Manga.mjs:153 _getUpdatedChaptersFromWebsite Error: Failed to receive content from "https://ganma.jp/api/2.0/magazines/a8e91de0-390d-11eb-a1a9-0a36bbec736b" (status: 404) - 
    at Connector.mjs:469

Ganma.mjs:66 Error: Failed to receive content from "https://ganma.jp/api/2.0/magazines/a8e91de0-390d-11eb-a1a9-0a36bbec736b" (status: 404) - 
    at Connector.mjs:469 

Well connector worked fine a week and a half ago
For the record, i can open the console in my browser in a chapter i want to download, i can do it manually by opening each page link individually, is just a problem in hakuneko that is not fetching anything beside the series list

**Screenshots**
https://i.imgur.com/Tgumb3L.png
https://i.imgur.com/HUpHOT7.png

**HakuNeko (please complete the following information):**
 - Version [6.17@0084ac]

### LINKED ISSUE #3850: [Manga Livre] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
error to download images from a chapter

**To Reproduce**

1. List a chapters with url https://mangalivre.net/manga/boku-no-hero-academia/1319
2.  click on a chapter for download
3. see the error 500 on req to list the images
4. Connector.mjs:618 Error: Failed to receive content from "https://mangalivre.net/leitor/pages/324381.json?key=5c029cc…" (status: 500) - 
    at Connector.mjs:469
    at async MangaLivre._getImageLinks (Leitor.mjs:98)
    at async MangaLivre._getPageList (Connector.mjs:615) 
EventTarget
5. the req (https://mangalivre.net/leitor/pages/324381.json) on hakuneko use a key like `5c8fe4e20253f6b9cca5b80e1d32d0eeef3619e8` and on browser the key like `165H889d3wcee839pb6UfeI215efI20i36U0esceo0em20u20N3e52eV1foc9R44t848sd9Ke1c6bD0eo69u1e653VeeVdbvf4t85f80325Oe00dcDc8Qe2O12931J37Pe2Bdc3z5dM3eu6eD1fp51bL0ekb5c63I86y3fe9bEafp3bMeee65M4aFdbSd6HceK61l8crffh0c5a8jdca8ep9Je1E31Se0kb22edMc9Vd0nb2b20Q87y9eIfbFa54JecC5339eW19L08ca9S4fCfchb2s5eScfne194t859ff` i think the key generator is old
**Screenshots**
image
image

**HakuNeko**
 - Version [e.g. 6.17@0084ac]

### LINKED ISSUE #3924: [Site Request] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Website has changed the manga list url from [https://www.jiangzaitoon.com/] to [https://www.jiangzaitoon.me/]

**HakuNeko**
 - Version 6.1.7@c86d92

### LINKED ISSUE #3929: [readmanga and mintmanga] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
nothing does not download 

**Screenshots**

**HakuNeko 
Version 6.1.7@c86d92

### LINKED ISSUE #3938: [1st Kiss Manga] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
When i refresh manga list to make it show new title, it show empty manga, but download is fine

### LINKED ISSUE #3943: [Site Request] Momo No Hana Scan
**Name of the website**
Momo No Hana Scan

**Website urls (examples below)**
- Site: https://momonohanascan.com/
- Manga List: https://momonohanascan.com/manga/
- Manga example: https://momonohanascan.com/manga/arasa-dakedo-hatsukoi-desu/
- Chapter online viewer example: https://momonohanascan.com/manga/arasa-dakedo-hatsukoi-desu/capitulo-56/

**Languages**
Portuguese

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
MadaraWordPress

### LINKED ISSUE #3945: [Site Request] https://manhwafull.com/
**Name of the website**
https://manhwafull.com/

**Website urls (examples below)**
- Site: https: https://manhwafull.com/
- Manga List: https://manhwafull.com/manga/
- Manga example: https://manhwafull.com/manga/light-and-shadow/
- Chapter online viewer example: https://manhwafull.com/manga/light-and-shadow/chapter-1/

**Languages**
List of languages supported by the website
English
**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

### PR DESCRIPTION
**Pull request by 27136773**
References:
- dazedcat19/FMD2#728
- dazedcat19/FMD2#729
- dazedcat19/FMD2#730

Resolves: #3801
Resolves: #3803
Resolves: #3825
Resolves: #3839
References: #3845
Resolves: #3850
Resolves: #3924

### CODE REVIEW

**Comment by 27136773** [comment]
Resolves: #3801

**Comment by 27136773** [comment]
Resolves #3803

**Comment by 27136773** [comment]
Resolves #3839

**Comment by 27136773** [comment]
References: #3845

**Comment by 27136773** [comment]
Resolves #3850

**Comment by 27136773** [comment]
Resolves: #3924

**Review by Sheepux — APPROVED** [review]

**Pull request merged**
