### PR TITLE
Update Nettruyen domain

### PR DESCRIPTION
**Pull request by Khangry**

### CODE REVIEW

**Comment by MikeZeDev** [comment]
First domain still works.  I dont see the need to change.

**Comment by Sheepux** [comment]
Current domain doesn't redirect, how do you know wich one is correct ?

**Comment by Khangry** [comment]
> First domain still works. I dont see the need to change.

it works when you live abroad but in Vietnam it is blocked

**Comment by Khangry** [comment]
> Current domain doesn't redirect, how do you know wich one is correct ?

I don't know, but sometimes the current domain work but sometimes it isn't. However, providers in Vietnam are very capricious :(

**Comment by MikeZeDev** [comment]
If you watch carefully, their manga list is not the same. One more reason not to change. 
image
image

Same page on both website, different content. Seems a clone to me, like we can see for many websites.

Given that this website just use a template without modifications its prob someone who download previous website content and made his own.

**Comment by Sheepux** [comment]
could be added as a connector setting (domain change)

**Pull request closed without merging**
