### PR TITLE
Update TruyenQQ.mjs

### LINKED ISSUE #5250: [TruyenQQ] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The website changed its domain to https://truyenqqvip.com/, but I changed it locally it doesn't work
**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by Khangry**
fix #5250

### CODE REVIEW

**Comment by MikeZeDev** [comment]
Fix lint errors then i can look into it.

**Comment by Khangry** [comment]
> Fix lint errors then i can look into it.

Sorry i forgot it 👍

**Comment by MikeZeDev** [comment]
LGTM.  Just a thing : we have the habit of using single quotes by default. Not that this will block anything but if you could fix that that would be great ^^

**Comment by Khangry** [comment]
> LGTM. Just a thing : we have the habit of using single quotes by default. Not that this will block anything but if you could fix that that would be great ^^

btw, about adding single quote into eslint rule?:>

**Review by MikeZeDev — APPROVED** [review]

**Pull request merged**
