### PR TITLE
Update SushiScan WebSite Connector

### LINKED ISSUE #4728: [Sushi Scan] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Impossible to read or download any manga from the website. Only the front page is visible.

I know the website changed, from sushi-scan.su to sushiscan.su but i dont know if this has been updated on Hakuneko.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

### PR DESCRIPTION
**Pull request by BenjaminKasprzak**
Following the latest new version of the sushiscan website, it'd be great to update the website constructor

### CODE REVIEW

**Review by Sheepux — APPROVED** [review]
/LGTM
However, remove the unneeded extra line at the end

**Comment by BenjaminKasprzak** [comment]
@Sheepux The blank line is not getting removed after my commits 🤔 
Anyway, be my guest for merging (I don't have the rights) 👍🏻

**Comment by Sheepux** [comment]
(yes i'll be the one to merge)
However, nothing changed, are you perhaps using github web editor ?

**Comment by BenjaminKasprzak** [comment]
> (yes i'll be the one to merge)
> However, nothing changed, are you perhaps using github web editor ?

Yes I am ! I should not ? 🤔

**Comment by Sheepux** [comment]
I think it's the online webtools that adds this new line. If you can try to use a local editor (vscode).
Just clone, commit and push to your branch https://code.visualstudio.com/docs/editor/versioncontrol#_cloning-a-repository

**Comment by BenjaminKasprzak** [comment]
Yeah, I use to do so in my job' ! I'll do it ! 👍🏻

**Comment by BenjaminKasprzak** [comment]
Hum, i may not have the right to push from my local branch to this or to a new branch 🤔 
Maybe you'll be able to update the file yourself locally ? 🤔

**Comment by Sheepux** [comment]
make sure you push from your own git, not hakuneko's ;)
this one: https://github.com/BKasprzakMeelo/hakuneko/tree/patch-1

**Comment by BKasprzakMeelo** [comment]
> make sure you push from your own git, not hakuneko's ;)
> this one: https://github.com/BKasprzakMeelo/hakuneko/tree/patch-1

Yeah, I am. But I says that I’m not allowed to push on this repo 😐

**Comment by BKasprzakMeelo** [comment]
I guess push force are not allowed on custom branches ?

**Comment by BenjaminKasprzak** [comment]
Youhou ! I'm good now ! 🥳 
Ping @Sheepux

**Pull request merged**
