### PR TITLE
ShueishaMangaPlus: api changes + fix getting chapters

### LINKED ISSUE #7110: [MANGA PLUS Shueisha] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Refreshing the manga list we get the following errors:

```
Invalid wire type 4 at offset 1
```

And in the console we get:

```
Connector.mjs:548 GET https://jumpg-webapi.tokyo-cdn.com/api/title_list/all 404
fetchPROTO @ Connector.mjs:548
async function (async)
fetchPROTO @ Connector.mjs:547
_getMangas @ ShueishaMangaPlus.mjs:37
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96

Connector.mjs:579 Error: invalid wire type 4 at offset 1
    at o.skipType (protobufjs.min.js:7)
    at m.Response$decode [as decode] (eval at h (protobufjs.min.js:7), <anonymous>:17:5)
    at m.decode (protobufjs.min.js:7)
    at ShueishaMangaPlus.fetchPROTO (Connector.mjs:550)
    at async ShueishaMangaPlus._getMangas (ShueishaMangaPlus.mjs:37)
    at async ShueishaMangaPlus._getMangaList (Connector.mjs:576) ShueishaMangaPlus {id: "shueishamangaplus", label: "MANGA Plus by Shueisha", tags: Array(4), isLocked: false, initialized: true, …}apiURL: "https://jumpg-webapi.tokyo-cdn.com/"config: {scrapeDelay: {…}}existingManga: [Black Clover: true, Blue Lock: true, Demon Slayer: Kimetsu no Yaiba: true, Golgo 13 (Viz Media Version): true, Lone Wolf & Cub: true, …]existingMangas: []id: "shueishamangaplus"initialized: trueisLocked: falseisUpdating: falselabel: "MANGA Plus by Shueisha"mangaCache: undefinedprotoTypes: "/mjs/connectors/ShueishaMangaPlus.proto"requestOptions: {method: "GET", mode: "cors", redirect: "follow", credentials: "same-origin", headers: Headers}rootType: "MangaPlus.Response"tags: (4) ["manga", "high-quality", "english", "spanish"]url: "https://mangaplus.shueisha.co.jp/"icon: (...)__proto__: Publus
_getMangaList @ Connector.mjs:579
async function (async)
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96
```

Version: master@54fbc6, Nightly build. Also happened in stable.

### To Reproduce

Refresh MANGA PLUS Shueisha Connector.

```
Invalid wire type 4 at offset 1
```

And in the console we get:

```
Connector.mjs:548 GET https://jumpg-webapi.tokyo-cdn.com/api/title_list/all 404
fetchPROTO @ Connector.mjs:548
async function (async)
fetchPROTO @ Connector.mjs:547
_getMangas @ ShueishaMangaPlus.mjs:37
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96

Connector.mjs:579 Error: invalid wire type 4 at offset 1
    at o.skipType (protobufjs.min.js:7)
    at m.Response$decode [as decode] (eval at h (protobufjs.min.js:7), <anonymous>:17:5)
    at m.decode (protobufjs.min.js:7)
    at ShueishaMangaPlus.fetchPROTO (Connector.mjs:550)
    at async ShueishaMangaPlus._getMangas (ShueishaMangaPlus.mjs:37)
    at async ShueishaMangaPlus._getMangaList (Connector.mjs:576) ShueishaMangaPlus {id: "shueishamangaplus", label: "MANGA Plus by Shueisha", tags: Array(4), isLocked: false, initialized: true, …}apiURL: "https://jumpg-webapi.tokyo-cdn.com/"config: {scrapeDelay: {…}}existingManga: [Black Clover: true, Blue Lock: true, Demon Slayer: Kimetsu no Yaiba: true, Golgo 13 (Viz Media Version): true, Lone Wolf & Cub: true, …]existingMangas: []id: "shueishamangaplus"initialized: trueisLocked: falseisUpdating: falselabel: "MANGA Plus by Shueisha"mangaCache: undefinedprotoTypes: "/mjs/connectors/ShueishaMangaPlus.proto"requestOptions: {method: "GET", mode: "cors", redirect: "follow", credentials: "same-origin", headers: Headers}rootType: "MangaPlus.Response"tags: (4) ["manga", "high-quality", "english", "spanish"]url: "https://mangaplus.shueisha.co.jp/"icon: (...)__proto__: Publus
_getMangaList @ Connector.mjs:579
async function (async)
_getMangaList @ Connector.mjs:576
(anonymous) @ Connector.mjs:99
Promise.then (async)
updateMangas @ Connector.mjs:98
onUpdateMangaListClick @ mangas.html:233
handler @ template-stamp.html:96
```

Version: master@54fbc6, Nightly build. Also happened in stable.

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/7110

### CODE REVIEW

**Comment by notoraptor** [comment]
Hello, here! Just a kindly reminder about this PR. As MangaPlus keeps only 3 last chapters, it would be fun to be able to get previous chapters using Hakuneko before they got deleted :D .

**Comment by 27136773** [comment]
There is another open PR #7175 for this website.
I think the reviewer has to decide which one should be merged.

**Comment by MikeZeDev** [comment]
Perhaps the other PR has good ideas, but i see it miss the updated langages id.

Its up to you to chose, boss.

**Comment by 27136773** [comment]
> Perhaps the other PR has good ideas, but i see it miss the updated langages id.
> 
> Its up to you to chose, boss.

I don't think i'll review any of these two PRs anytime soon 🙈

**Comment by 27136773** [comment]
Suggestion to close PR after **Monday, 19 August 2024** (12 weeks) if not approved by a reviewer.

**Pull request closed without merging**
