### PR TITLE
add connector monzeekomik

### LINKED ISSUE #6929: [Site Request] Monzee Komik
**Name of the website**
Monzee Komik

**Website urls (examples below)**
- Site: https://monzeekomik.my.id/
- Manga List: https://monzeekomik.my.id/manga/
- Manga example: https://monzeekomik.my.id/manga/the-son-of-the-first-emperor-kills-enemies-and-becomes-a-god/
- Chapter online viewer example: https://monzeekomik.my.id/the-son-of-the-first-emperor-kills-enemies-and-becomes-a-god-chapter-56-bahasa-indonesia/

**Languages**
Indonesian

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

### PR DESCRIPTION
**Pull request by akn19**
Fixes https://github.com/manga-download/hakuneko/issues/6929

### CODE REVIEW

**Comment by MikeZeDev** [comment]
I am gonna add this to Haruneko when i have the time then ill approve this

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
Manga title got junk "bahasa indonesia" at the end. 

It should be removed.

```
    async _getMangas() {
        const mangas = await super._getMangas();
        mangas.forEach(manga => manga.title = manga.title.replace(/Bahasa Indonesia$/i, '').trim());
        return mangas;
    }
```

**Comment by akn19** [comment]
> Manga title got junk "bahasa indonesia" at the end.
> 
> It should be removed.
> 
> ```
>     async _getMangas() {
>         const mangas = await super._getMangas();
>         mangas.forEach(manga => manga.title = manga.title.replace(/Bahasa Indonesia$/i, '').trim());
>         return mangas;
>     }
> ```

done

**Comment by MikeZeDev** [comment]
You changed the wrong file

**Pull request closed without merging**
