### PR TITLE
[MangaHub] Add getting API key

### LINKED ISSUE #4874: [MangakakalotFun] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Cannot acces using hakuneko but can be accessed using browser

**To Reproduce**
1. MangakakalotFun
2. all manga titles showing and working but all chapters on all manga is not showing
3. Failed to recieve content (status 403)

**Screenshots**
Untitled

**HakuNeko (please complete the following information):**
 - Version 6.17

### LINKED ISSUE #4896: [MangaHub] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
- HakuNeko is not detecting the Chapter list nor of undownloaded pages.

**To Reproduce**
1. Name of connector
- MangaHub
2. Name of manga (if connector update is working)
- All 
3. Name of chapter (if manga update is working)
- All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
- Something about the API key being invalid or expired error. See screenshot.

**Screenshots**
Errors

**HakuNeko (please complete the following information):**
 - Version [8.3.4] or [2022 HakuNeko rev. master@81f06c]

### PR DESCRIPTION
**Pull request by Druzai**
Got it working by getting cookie with API key, but some users said that they can't load the site page due to CloudFlare issue, so they might not receive this cookie because the page doesn't load when connector is initializing.

So I would like to ask someone else to test this code on their machine to make sure it works.

Also retrieving manga via clipboard feature won't work because of CloudFlare too.

Resolves #4896
Resolves #4874

### CODE REVIEW

**Comment by EnforcerRidley** [comment]
> So I would like to ask someone else to test this code on their machine to make sure it works.

How would I go about doing that?

**Comment by Druzai** [comment]
If you don't want to clone this repository or my fork (I haven't done this with others PRs), checkout this PR with Github Desktop and set up the enviroment [(all steps are written here)](https://github.com/manga-download/hakuneko/wiki/Developer-Manual), then you can add new code using a text editor to connector in path `%cache_folder%/mjs/connectors/MangaHub.mjs` and restart HakuNeko.
[Path to cache folder](https://hakuneko.download/docs/install/#cache)

**Comment by EnforcerRidley** [comment]
I have windows so `%cache_folder%` would be `%USERPROFILE%\AppData\Local\hakuneko-desktop\cache`, so the full path would be… `%USERPROFILE%\AppData\Local\hakuneko-desktop\cache\mjs\connectors\MangaHub.mjs`, right, like so:
Path_to_Cache-MangaHub0001
And I edited MangaHub.mjs with you code in order to make it exactly the way you have it.

I've also followed the instructions and installed gut, NODE.JS, and NVM successfully. I already have Notepad++ and I can even edit the code within HakuNeko itself, which is how I added your code, then saved it to `%USERPROFILE%\AppData\Local\hakuneko-desktop\cache\mjs\connectors\MangaHub.mjs`.

I restarted Hakuneko and tried any MangaHub manga and… nothing… I'm still getting the same error.

Perhaps, I did something wrong?

I guess I try with downloading the whole thing, following the full instructions and not just setting up the environment.

**Comment by Druzai** [comment]
> I've also followed the instructions and installed gut, NODE.JS, and NVM successfully.

You didn't have to install it, if you just decided to edit the connector in cache folder...

First, when you're searching for `mangahub`, connector appears in list of connectors?
image
And in console there are some error messages (F12)?

> I guess I try with downloading the whole thing, following the full instructions and not just setting up the environment.

Wait, maybe you're just copied code wrongly?

**Comment by EnforcerRidley** [comment]
>You didn't have to install it, if you just decided to edit the connector in cache folder...

I had to add what's in the cache folder though. Is that not how it's supposed to be?

> First, when you're searching for `mangahub`, connector appears in list of connectors? image 

Yes.

>And in console there are some error messages (F12)?

Error0001
Error0002

**Comment by Druzai** [comment]
Yes, I get it too...
Also tested on portable version and get an error. But it worked on development version, sorry.
I'll think how to solve this issue.

**Comment by EnforcerRidley** [comment]
I'm not able to get the changes within HakuNeko itself though. The MangaHub.mjs (f12) doesn't have your changes and I don't know how to get it to read the one with your changes even though I can save the changes. I saved the edited MangaHub.mjs into `%USERPROFILE%\AppData\Local\hakuneko-desktop\cache\mjs\connectors\` but the changes won't stick and restarting HakuNeko just resets MangaHub.mjs to what's already in the git.

**Comment by Druzai** [comment]
Figured, you have to copy changes for [Connector.mjs](https://github.com/manga-download/hakuneko/blob/cdd5f6f11c289c4600966d388c5678d0bef45bf9/src/web/mjs/engine/Connector.mjs), those changes for convenience [here](https://github.com/manga-download/hakuneko/commit/d8edf21aae2c624d89d235a49f38698936900ec4#diff-88c2c925a0d5fa6b8d9b267fe6225ce1298cd58b416f70ca439203934bf6e630).

If you're using 6.1.7 or nightly version, so you don't have some important changes.

**Comment by Druzai** [comment]
> I'm not able to get the changes within HakuNeko itself though. The MangaHub.mjs (f12) doesn't have your changes and I don't know how to get it to read the one with your changes even though I can save the changes. I saved the edited MangaHub.mjs into %USERPROFILE%\AppData\Local\hakuneko-desktop\cache\mjs\connectors\ but the changes won't stick and restarting HakuNeko just resets MangaHub.mjs to what's already in the git.

Wait, you're changing files for `6.1.7` or nightly version, but running development version that was cloned via git.
Run your stable version or change connector in development version (path - `%hakuneko%\src\web\mjs\connectors\MangaHub.mjs`) and run development version.

**Comment by EnforcerRidley** [comment]
Ok, I just completed what's in the [Developer-Manual](https://github.com/manga-download/hakuneko/wiki/Developer-Manual), altered it's MangaHub.mjs, launched the Developer HakuNeko and now it works.
DevTest_Success0001
So we do know your changes work at least in the Development version but not the Installed version.

> You're using 6.1.7 version, so you don't have some important changes.

But I'm using version 8.3.4.

**Comment by Druzai** [comment]
> But I'm using version 8.3.4.

That's strange cause Connector.mjs have been fixed in development and `8.3.4` version (in other words - nightly version) get all new commits from `master` branch...

Well, good to know its working not only for me :)

**Comment by EnforcerRidley** [comment]
Hmm… HakuNeko Dev version with your code just got the API key error, but restarting HakuNeko Dev fixes the problem.

**Comment by Druzai** [comment]
Maybe connector didn't initialize header with MangaHub API key...

If you encounter this error again, could you check failed request in `Network` tab?
Correct response has highlighted header.
image
That request with 403 error must be missing header `x-mhub-access`.
But anyway it would be good to know what caused the error this time.

**Comment by Druzai** [comment]
Also it might be this error: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12982
Should I add throttling of API requests like in `MangaDex` connector to prevent hitting rate-limit?
https://github.com/manga-download/hakuneko/blob/cdd5f6f11c289c4600966d388c5678d0bef45bf9/src/web/mjs/connectors/MangaDex.mjs#L16-L22

**Comment by EnforcerRidley** [comment]
> Maybe connector didn't initialize header with MangaHub API key...
> 
> If you encounter this error again, could you check failed request in `Network` tab? Correct response has highlighted header. 

Error0003-Marked
Is this the correct header?

> Also it might be this error: [tachiyomiorg/tachiyomi-extensions#12982](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12982) Should I add throttling of API requests like in `MangaDex` connector to prevent hitting rate-limit?

I'm not really to one to ask as I don't have much knowledge in programing, but, according to the error message, it may be a good idea considering too many requests seem to be getting that error, however wait a while and the error goes away for the same Manga/Chapter.

If it turns out it doesn't help, we can always undo the changes, correct?

**Comment by Druzai** [comment]
Yes.

**Comment by Sheepux** [comment]
> That request with 403 error must be missing header `x-mhub-access`.

This could be the cloudflare page itself and not the API response (check the response html code). If that's the case, then it's the "unsolved cloudflare issue"

**Comment by EnforcerRidley** [comment]
What can be done about the Cloudfare issue: update electron dependency for HakuNeko? I feel that it's not so simple or would that not have been done already?

**Comment by Sheepux** [comment]
Regarding cloudflare, nothing can be done without to much work: see #2933
This is why haruneko is being worked since 2 years ago (hakuneko full rewrite).

**Comment by EnforcerRidley** [comment]
That's unfortunately what I figured. Sorry for the stupid question.

**Comment by vetleledaal** [comment]
Throttling wouldn't help much, you should instead emulate what the site does. When it receives an error from the API, it loads `https://mangahub.io/manga/some-manga?reloadKey=1`, where it gets a new API key from a cookie, which is then used against the API.

I guess you can fetch the new API key before you get an error, but this might be detectable, or they may change the limit, so you're stuck implementing retrying either way.

Feel free to check out how I implemented it for Tachiyomi, if you don't mind the fluff https://github.com/tachiyomiorg/tachiyomi-extensions/pull/13012

**Comment by Druzai** [comment]
@vetleledaal Thanks for the help and for sharing your code!

I wrote code for updating the API key, but I'm stuck with Cloudflare issue again, when I try to receive a new API key. :)
So I guess request throttling is the only way left, if users don't want to get errors, when downloading a big list of chapters.

Also I noticed that if you request a URL **with chapter**, you receive a new API key on every request, even if you sending these requests every second, example - `https://mangahub.io/chapter/some-manga/chapter-1?reloadKey=1`.
And without chapter you can receive a new API key only at certain intervals (every minute or so).

**Comment by vetleledaal** [comment]
For the Cloudflare issue it appears to be something custom with MangaHub, as the issues went away in Tachiyomi after adding additional headers https://github.com/tachiyomiorg/tachiyomi-extensions/pull/12938.

I would assume that not all headers are required, but since they started blocking based on headers I just added whatever Edge sends out (default Tachiyomi UA).

**I would try removing the Origin header first**, and only use it for the API.


> Also I noticed that if you request a URL with chapter, you receive a new API key on every request, [...]

Good to know, but with the current structure it would be a bit awkward to implement. I'll revisit this if the current solution is insufficient.

**Comment by Druzai** [comment]
> For the Cloudflare issue it appears to be something custom with MangaHub, as the issues went away in Tachiyomi after adding additional headers https://github.com/tachiyomiorg/tachiyomi-extensions/pull/12938.

No, it's not headers. It's a problem with the old version of electron, which can't solve Cloudflare challenge and gets stuck in an infinite loop. I already added those headers in #4876 and #4890.

**Comment by Druzai** [comment]
I guess, I figured out how not to trigger Cloudflare challenge. If you use `fetch` instead of `Engine.Request.fetchUI`, you get new cookie without loading UI and triggering this protection afterwards.
But I can't get header `set-cookie` in response, although when response is being parsed in handler this header is present.
https://github.com/manga-download/hakuneko/blob/cdd5f6f11c289c4600966d388c5678d0bef45bf9/src/web/mjs/engine/Request.mjs#L519-L549
Is there some way to retrieve this header or a cookie without loading page of MangaHub?
Or it's just an electron issue?

**Comment by vetleledaal** [comment]
> No, it's not headers. It's a problem with the old version of electron, which can't solve Cloudflare challenge and gets stuck in an infinite loop.

Right, my bad. The challenge page is only shown if the UA reports some variant of Chrome. After testing a few variants it looks like the challenge is only shown when your UA matches the regex:
```regex
/ Chrome\/\d+\.\d+\.\d+(?:\.\d+)?[^ ]* Safari\/\d+(?:\.\d+)?[^ ]* *$/
```
You should probably just use a Firefox UA to skip the challenge

> Is there some way to retrieve this header or a cookie without loading page of MangaHub?
Or it's just an electron issue?

I'm not too familiar with JS development, but could this be a limitation of `fetch()`?

**Comment by Druzai** [comment]
> I'm not too familiar with JS development, but could this be a limitation of `fetch()`?

I read that by default you can't get or set some headers, if browser's web security is enabled. But in Hakuneko web security is disabled for all requests.

> You should probably just use a Firefox UA to skip the challenge

Using only Firefox UA works, thanks! Then I'll try to get new API key from cookies.

**Comment by Druzai** [comment]
> I'm not too familiar with JS development, but could this be a limitation of `fetch()`?

I came to the conclusion that when the `Headers` object is created, some headers are removed, and `set-cookie` header is among them. I created a workaround: I copy `set-cookie` header to a custom one - `x-set-cookie`, and it doesn't get removed.

And now I don't need Firefox UA anymore.
Also clipboard feature is working again.

**Comment by EnforcerRidley** [comment]
These new changes seem to make the chapters and pages load faster and there API key error no longer seems to appear when downloading chapters in bulk or loading another undownloaded chapter from a different manga. It seems all the issues with HakuNeko seem fixed at least in the Dev version.

**Comment by Druzai** [comment]
They changed mechanism to update API key. They clear API key in the cookies and request a new one again.
I'll try to search for a new solution.
GraphQL error is slightly different now: `API rate limit excessed! Go to mangahub.io to continue reading!`.

**Comment by EnforcerRidley** [comment]
It's almost as if MangaHub is trying to make sure HakuNeko and other similar programs don't work on their site.

**Comment by 27136773** [comment]
May consider using `fetchUI` instead of using `GraphQL`

**Comment by Druzai** [comment]
> May consider using `fetchUI` instead of using `GraphQL`

I will switch if there is no other way.

@ronny1982, I also wanted to speed up process to set new cookies. Can I do that? - 35cd22597498b894d15a05edb7d362fef3866c6e
I can revert that commit if it is contrary to the code style of the project.

**Review by 27136773 — APPROVED** [review]
As you already mentioned, probably not the best solution to map response cookies. Would be better to extract them for every response and add them to the corresponding cookie jar for the domain, so this would apply to all websites and not just to MangaHub.

However, with the development of the successor it makes not much sense to invest much more into the current version of HakuNeko.

**Pull request merged**
