### PR TITLE
fix MangaSect source

### PR DESCRIPTION
**Pull request by kajack**
* Fix MangaSect source site.

### CODE REVIEW

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
This is overcomplicated for nothing i think.

1) Mangasect.com is now mangasect.net you should change url. 
2) They changed manga template, its now what we call "MojoPortalComic"
3) Fix lint errors

I'd suggest to check how are coded MojoPortalComic websites we already support in hakuneko.

There is no need for an overcomplicated getpages, at least in Haruneko i managed to code it with standard code (css on page)

**Comment by kajack** [comment]
Ups, right forgot about Lint.

Alright will check those MojoPortalComic

**Comment by MikeZeDev** [comment]
Ok i have made a fix on your repo, a custom getpages was just needed tell me if that works :p

https://github.com/manga-download/hakuneko/pull/6930/commits/51f081cbadcf6e2bfe698293b1240acb998a7968

**Comment by kajack** [comment]
Yeah worked. Indeed, cleaner and easier than the code I had done.

**Review by MikeZeDev — APPROVED** [review]

**Pull request merged**
