### PR TITLE
[xunscans] fix url

### LINKED ISSUE #3652: [XuNScans] Connector not working
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Neither Chapter, nor Mangas are showing. I've tried using the clipboard function too, but it doesn't show any chapters from that manga link. I've also tried reloading the connector but it only spins for 1-2 secs and then stops spinning without any error message. I can however open and navigate the connector by using in-built browser of HakuNeko, but I can't use the connector to download or read. 

**To Reproduce**
1. XuNScans
2. None of the manga is showing ( connector update is not working)
3. None of the chapter is shwoing (even if I copy the link of manga from XuNScans, it won't show me the chapters)
4. No error message pops up.

**Screenshots**
image

**HakuNeko (please complete the following information):**
 - Version 6.17

### PR DESCRIPTION
**Pull request by XenonR**
Closes #3652

### CODE REVIEW

**Comment by XenonR** [comment]
uhh. that went into the wrong branch. only thing changed is https://github.com/manga-download/hakuneko/pull/3653/commits/c23bdd44c070d60d11d986bd40a4e51dcd7cd485

**Comment by andrehadianto** [comment]
do u have a fork for this?

**Comment by XenonR** [comment]
> 
> 
> do u have a fork for this?

yes, you are looking at it 😉 (https://github.com/manga-download/hakuneko/commit/c23bdd44c070d60d11d986bd40a4e51dcd7cd485). anyways, save yourself some time it will most likely be merged today.

**Comment by 27136773** [comment]
Sync branch by pulling from `manga-download/hakuneko master`

**Review by 27136773 — APPROVED** [review]
Looks good

**Pull request merged**
