### PR TITLE
japanread chapter pagination

### LINKED ISSUE #3561: [japanread] Connector not working
hello sir can you please check, 'mangakawaii'hello sir please check japanread.cc

### PR DESCRIPTION
**Pull request by Sheepux**
Solves #3561
chapter list pagination fixed

However i'm stuck with the image retrieval that seems cloudflare protected: http 403 (it doesn't look like the global challenge).
@ronny1982  Any tricks for this last part ? (you can also push the fix in the HN branch)

### CODE REVIEW

**Review by 27136773 — APPROVED** [review]
Looks good

**Comment by Sheepux** [comment]
> Looks good

Yeah, but it's still a draft as the images aren't retrieved due to a cloudflare security check and i don't know how to bypass it

**Comment by 27136773** [comment]
Seems like `referer` must be the chapter containing the image
```bash
curl 'https://www.japanread.cc/images/mangas/chapters/151280/japanread_yojouhan-isekai-kouryuu-ki_ch6.2_60cf5c0f35256.jpg' -H 'referer: https://www.japanread.cc/manga/'
```

May try same solution as in [ScanTrad](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/ScanTrad.mjs#L44-L59)

**Comment by Sheepux** [comment]
That solved the case. Thanks !

**Pull request merged**
