### PR TITLE
FIX RandomScan : change url

### LINKED ISSUE #5031: [randomscans] Chapters cannot be downloaded!!!!!
Chapters cannot be downloaded, gray folder!!!!

Site New: randomscans.com

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/5031

(As there is no cloudflare for now)

### CODE REVIEW

**Comment by Sheepux** [comment]
redirects to .net and doesn't work :\

**Comment by MikeZeDev** [comment]
> redirects to .net and doesn't work :\

I swear it was .com when i pushed the commit :D . oh well : file updated.

**Comment by Sheepux** [comment]
I mean ... it redirect to .net but the website itself does not work in my browser

**Comment by MikeZeDev** [comment]
hu? works for me

**Review by Sheepux — APPROVED** [review]
/Blind Approval

**Pull request merged**
