### PR TITLE
Add imperiodabritannia Connector

### PR DESCRIPTION
**Pull request by Lapot300**

### CODE REVIEW

**Comment by 27136773** [comment]
Suggestion to close PR after **Tuesday, 4 February 2025** (12 weeks) if not approved by a reviewer.

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
* Code is ok
* icon must be a png not a jpeg . Please convert the picture to png and its good.

**Comment by Lapot300** [comment]
@MikeZeDev Thanks for the heads-up, I converted the image as you requested.

**Review by MikeZeDev — APPROVED** [review]
Thanks for your contribution.👍 

Next time perhaps try to add it to [Haruneko ](https://github.com/manga-download/hakuneko) directly ?

**Pull request merged**
