### PR TITLE
Fixes Piccoma & PiccomaFR

### LINKED ISSUE #6430: [Piccoma France] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

@Elastic1 Hi dude, Piccoma changed their scrambeling method ig, here is an example of what I get rn : 

image

If you could try to check this I would really appreciate 🙏 thx in advance
### To Reproduce

1. PiccomaFR
2. any manga

### LINKED ISSUE #6627: [<Piccoma.com>] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

When I select the manga, its chapters do not appear.
Captura de pantalla 2023-12-29 105029

### To Reproduce

Captura de pantalla 2023-12-29 105029

3. Name of chapter (if manga update is working)

### PR DESCRIPTION
**Pull request by MikeZeDev**
* Fixes https://github.com/manga-download/hakuneko/issues/6430 (descrambling). Bonus : its simpler
* Fixes https://github.com/manga-download/hakuneko/issues/6627
* Add manga list for PiccomaFR
* Fix clipboard 
* Better mangalist for Piccoma (but it takes way more time)

Fixes are inspired from Haruneko plugins for Piccoma, <3 ronny

### CODE REVIEW

**Comment by onelots** [comment]
hmmmm it has been opened 2 weeks ago, is there something that blocks the merge ?

**Comment by MikeZeDev** [comment]
> hmmmm it has been opened 2 weeks ago, is there something that blocks the merge ?

reviewers real life

**Review by Hachdog — APPROVED** [review]

**Comment by onelots** [comment]
hmmm since it's approved, should'nt it be merged automatically ?

**Comment by MikeZeDev** [comment]
> hmmm since it's approved, should'nt it be merged automatically ?

Approval by random people is useless, i even wonder why they can do that

**Comment by onelots** [comment]
lol ok I was like "who's this new admin ?"

**Comment by Hachdog** [comment]
> lol ok I was like "who's this new admin ?"

Ahah sorry about that, I was wondering how approving worked. Wasn't expecting it to go all the way ... :P

**Pull request closed without merging**
