### PR TITLE
Add noindexscan Connector

### PR DESCRIPTION
**Pull request by Lapot300**

### CODE REVIEW

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
It doesnt work. 

Website got anti ddoss mechanism, check in your browser

image

You submitted it without testing = you lost your time, and maintainers time.

**Comment by Lapot300** [comment]
@MikeZeDev I tested it directly in the program, I downloaded 3 entire mangas, more than 500 chapters in total without any problems.

**Comment by MikeZeDev** [comment]
Not only i knew it shouldnt work, but it didnt work.

image

Its working for you because you somehow opened the website in Hakuneko internal browser and got the cookie that bypass the anti ddoss script. This is something we cant reasonably ask for the user to do.

Try overriding  _initializeConnector and call fetchui with an appropriate delay in script to pass the anti ddoss

**Comment by MikeZeDev** [comment]
Eventually, Haruneko can handle such problem easily, and adding a madara website is kinda easy if you want ^^

**Comment by Lapot300** [comment]
I'll look into this, I'll keep the pull request closed until I can implement a viable solution. Thanks for the tip.

**Pull request closed without merging**
