### PR TITLE
[WordPressMadaraNovel] Implement _getMangaFromURI

### LINKED ISSUE #2290: Manga Name Error while Using Clipboard method[Bug]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When i copied the manga url and the clicked the clipboard icon it loaded the manga which i wanted but there was a bug and the manga name didnt show. I tried multiple time but the name didnt show properly. I restarted multiple times too and usend tother websites to test. unfortunately the name didnt show.

**To Reproduce**
1. Go to 'https://wuxiaworld.site/novel/kill-the-hero-comic/'
2. Copy the url : 'https://wuxiaworld.site/novel/kill-the-hero-comic/'
3. Open HakuNeko and Click Clipboard Icon

**Expected behavior**
I expected to see the manga name!

**Screenshots**
error name png

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [6.17] Stable Latest

**Additional context**

### PR DESCRIPTION
**Pull request by XenonR**
Closes #2290

### CODE REVIEW

**Review by 27136773 — COMMENTED** [review]
Would it make more sense to move the method into the base class `WordPressMadara`, so all Madara based connectors could use this and not just Madara Novel?

Many Madara (Novel) based websites may not work correctly after this update, because the CSS query may be different for each website, but i don't see this as show stopper, as fetching the manga list is usually faster for these websites then using copy & paste.

**Comment by XenonR** [comment]
Idk tbh. How similar are the novel vs. non-novel sites? Relying on your experience here. If you say it makes more sense to integrate it into `WordPressMadara` I can do so.

**Comment by 27136773** [comment]
Seems most Madara and MadaraNovel websites provide title by the last `og:title` meta tag, so i would go with this
`[...document.querySelectorAll('head meta[property="og:title"]')].pop().content`

**Comment by XenonR** [comment]
> 
> 
> Seems most Madara and MadaraNovel websites provide title by the last `og:title` meta tag, so i would go with this
> `[...document.querySelectorAll('head meta[property="og:title"]')].pop().content`

Works too and is certainly more universal. Some sites do add the site name after the title, but that should be fine as long as it is consistent (per conenctor).

**Review by 27136773 — APPROVED** [review]
Looks good

**Pull request merged**
