### PR TITLE
[mangatoro] added website support

### LINKED ISSUE #3631: [Site Request] Mangatoro (former Mangahua)
**Name of the website**
Mangatoro

**Website urls (examples below)**
- Site: https://ja.mangatoro.com/
- Manga List: https://ja.mangatoro.com/genres
- Manga example: https://ja.mangatoro.com/manga/senritsu-no-majutsushi-to-goteijuu-128
- Chapter online viewer example: https://ja.mangatoro.com/manga/senritsu-no-majutsushi-to-goteijuu/chapter-21/55655

**Languages**
Site is in English. Raws in Japanese

**Website relationship*
It was known as Mangaua.com. Some weeks ago they changed the name to mangatoro and the structure, using subdomains: en.mangatoro.com for manga in english, jp.mangatoro.com for raws in japanese
Actually, mangahua.com is redirected to mangatoro.com

**Additional details**
Maybe reuse the Mangahua template?

### PR DESCRIPTION
**Pull request by 27136773**
Replaces
- MangaHua
- MangaNT

### CODE REVIEW

**Review by XenonR — APPROVED** [review]
All works, all good.

**Comment by vvirtual** [comment]
Hello! Thanks for fixing this connector. May I ask when will it be available in the app? I can't see it when I run the app (and Mangahua is sill in).
Thanks you very much for your hard work!!

**Comment by 27136773** [comment]
Use nightly build or wait until it is synced into 6.1.7 in a few weeks

**Comment by vvirtual** [comment]
Hi again! I've installed night build. It doesn't seems to be working to download RAW. It does not accept URL's from mangatoro. The reason I guess it's because Mangatoro divided the web in two different sites: en.mangatoro.com (english mangas) and ja.mangatoro.com (raw mangas).
Example: https://ja.mangatoro.com/manga/ry-kusari-no-orishin-no-naka-no-kokoro-1166
IIt's not accepted by HakuNeko clipboard. Probably because it doesn't include "www.mangatoro.com" but "ja.mangatoro.com" (my guess).
Thanks for your great work and effort!

**Comment by 27136773** [comment]
I recommend to open a ticket stating to add copy and paste support for `en` and `ja` subdomains on mangatoro

**Pull request merged**
