### PR TITLE
Fix CocoManhua/MangaDig : defeat encryption again

### LINKED ISSUE #6468: [<CocoManHua>] Connector not working
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Images are missing in the embeded viewer

### Describe the bug

Cannot preview/download chapter, the downloaded file is broken
WM-Screenshots-20231129211656
WM-Screenshots-20231129211746

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

### PR DESCRIPTION
**Pull request by MikeZeDev**
Fixes https://github.com/manga-download/hakuneko/issues/6468

see relevant commit : https://github.com/manga-download/hakuneko-plugins/commit/a3a2535a8194cdc7b6960f9c0da318288d2ddf56

### CODE REVIEW

**Comment by MikeZeDev** [comment]
Deleted irrelevant message complaining "its not working in Hakuneko" . 

* The fix isnt available to the user so its normal
* Its not the place for such message anyway, unless the person tried the fix from the PR, which wasnt probably the case.

**Comment by black0888** [comment]
so I just need to wait the connector update automatic from pull request?

**Comment by MikeZeDev** [comment]
Use nightly and wait. This is something you ask on the issue itself not on the PR.

**Review by Sheepux — APPROVED** [review]
/LGTM

**Pull request merged**
