### PR TITLE
Improve parallelization of Hentai2Read connector

### PR DESCRIPTION
**Pull request by Bitverdreher**
Yaaz

### CODE REVIEW

**Comment by 27136773** [comment]
The website has a paginated manga list with `754` pages. Creating so many requests at the same time is a very bad idea for the following reasons:
- HakuNeko may become unresponsive
- Users may hit a server side rate limit with worst case of IP ban

Therefore i would suggest to abandon this change

**Comment by Bitverdreher** [comment]
Technically, chromium should restrict the amount of requests sent to one host at a time - so in practice it would 'only' mean, that the load for the server will only increase by a factor of 6 - that should also be the speedup.

**Comment by 27136773** [comment]
I tested it in HakuNeko by injecting
```javascript
(async function() {
	const promises = new Array(750).fill().map((_, index) => fetch(`https://hentai2read.com/hentai-list/all/any/all/name-az/${index + 1}/`));
	await Promise.all(promises);
})();
```

**PRO:**
The saved time is really astonishing, it is like 100 times faster then scraping page py page.

**CON:**
On the other hand chrome blocked any other request while the manga list was syncing, due to chromes internal scheduler (other requests such as browsing chapters in the UI are blocked until the manga list sync was completed).

**NOTE:**
The next version of HakuNeko will have a [TaskPool](https://github.com/manga-download/haruneko/tree/master/src/engine/taskpool) with support for configurable concurrency and rate limiting, which is well suited to solve such problems.

**Comment by 27136773** [comment]
Dropped for HakuNeko.
The next iteration has the aforementioned ability of better control for multiple concurrent requests and rate limiting, which can be used to increase performance for manga list updates from such websites...

**Pull request closed without merging**
