### PR TITLE
[Tappytoon] Fix getting paid chapters

### LINKED ISSUE #4906: [Tappytoon (English)] Only free chapters are displayed despite login
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Through Tappytoon english, only the freely available chapters are listed, despite most series containing more than those freely available chapters and despite logging into an account that has those paid chapters unlocked already.

**To Reproduce**
1. Tappytoon (English)
2. Any series that does not fully contain chapters labelled as FREE
3. Comparing the chapter list produced by HakuNeko vs total available chapters

**Screenshots**
Chapter list by HakuNeko: https://i.imgur.com/khjGSCB.png
Sample Chapter list: https://i.imgur.com/r1WQGYx.png
>Chapters marked Free and those with a checkmark (Paid chapters that were unlocked)
>>Having the chapter unlocked changes nothing vs locked

**HakuNeko (please complete the following information):**
 - Version [6.1.7@7ed275]

### PR DESCRIPTION
**Pull request by Druzai**
Resolves #4906

### CODE REVIEW

**Comment by onelots** [comment]
I just tried it to maybe close the pr, but It doesnt seem to work... I've the same problem, which is that when I refresh, i just have free chapters showns.

**Comment by Druzai** [comment]
1) After you logged in with your tappytoon account in Hakuneko. Did you restart Hakuneko before retrieving manga list?

2) Have you changed code to this?
https://github.com/manga-download/hakuneko/pull/5066/files#diff-6868ca91ea021f9f9073223f4d3a994333d07d0da243ffd6f9981ff2894ec15cR57-R67

3) If first two steps were done then it must be problem with my code.
I only tested it on rented chapters, so it would be great if you could send me the content of the response that gets manga list with purchased chapters. And information about which chapters you purchased.

Steps to get response content (this content doesn't have sensitive info, only list of manga chapters):
F12 -> `Network` Tab -> `chapters` request -> Response Tab -> Copy that text (Ctrl + A, Ctrl + C) and please save it in file

That request URL must be similar to this - `https://api-global.tappytoon.com/comics/515/chapters`.
(You can check it in `Headers` Tab)

image

**Comment by onelots** [comment]
> 

1 - yes, I rebooted hakuneko after logging in.

2 - I used your repo directly to be sure to have the corrected version :)

would you mind use discord instead of github to discuss ? I would feel more free and it's easier to talk with it :) 
my tag is `Onelots.#0007`
I'm waiting for your response. Btw, I will do what you said above with the requests.

**Review by onelots — APPROVED** [review]
Should be good, I actually made an error testing the code but it works fine actually.

**Review by Sheepux — APPROVED** [review]
/LGTM

**Pull request merged**
