### PR TITLE
Update SushiScans url

### PR DESCRIPTION
**Pull request by FedorRadionenko**

### CODE REVIEW

**Comment by MikeZeDev** [comment]
Does it works after changing url? I bet it doesnt. Cloudflare crap. Maybe useless PR 🤷

**Comment by FedorRadionenko** [comment]
> Does it works after changing url? I bet it doesnt. Cloudflare crap. Maybe useless PR 🤷

Honestly, I did not test it. But it is surely not working now, so i decided to try just pull request. Purely for luck.

**Comment by FedorRadionenko** [comment]
Site url is valid though.

**Comment by MikeZeDev** [comment]
Yeah, gonna merge that anyway

**Review by MikeZeDev — APPROVED** [review]

**Pull request merged**
