### PR TITLE
Added FMTeam scanlation connector

### PR DESCRIPTION
**Pull request by Albirew**

### CODE REVIEW

**Comment by Albirew** [comment]
Actually, FMT is the successor team of Scantrad. May want to remove `ScanTrad.mjs` connector since it doesn't exist anymore...

**Comment by 27136773** [comment]
Don't forget to add the corresponding icon

**Comment by Albirew** [comment]
aaand it's done 👍

**Review by 27136773 — APPROVED** [review]

**Comment by 27136773** [comment]
[Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27fmteam%27&type=code)

**Pull request merged**
