### PR TITLE
FIX - Fix Streamtape and add some video hosters

### PR DESCRIPTION
**Pull request by MikeZeDev**
Exemple video streamtape/com/e/jvbVlqXddzuzZJJ/

### CODE REVIEW

**Comment by MikeZeDev** [comment]
Those are needed for a future anime connector.

**Comment by MikeZeDev** [comment]
Same reasons than for Dood PR : those unused video hosters are used and works in future PR. In the meantime they may be useful to other people.

**Review by Sheepux — APPROVED** [review]
LGTM but i don't know the video connectors at all so i don't know what issues it could contains

**Comment by MikeZeDev** [comment]
> LGTM but i don't know the video connectors at all so i don't know what issues it could contains

Streamtape is just simulating click to load the video and get its url from played. I fixed the CSS element to click.
Others are unused for now anyway, and here for future connectors.

**Pull request merged**
