### PR TITLE
[LINE Manga (LINEマンガ) ] add website support

### LINKED ISSUE #147: Add support for website: LINE Manga (LINEマンガ) [JA]
This is the official Japanese version of Naver's **LINE Webtoon**. (HakuNeko already has all the other versions: Korean/English/Indonesia/Thai/Viet)

**Site name**: LINE Manga (LINEマンガ)
**URL**: https://manga.line.me/

**Language**: Japanese

**Content**: Webtoons and mangas in Japanese

**Free**: Partially. The first few chapters are free. For the rest, you can either wait a day to access another free chapter for a week OR pay coins to read immediately.

**Require account/login**: Yes. (Apparently, needs a LINE account which is either: linked to a Japanese phone number OR not linked to any phone number but linked to Facebook)

**Require Japan IP address**: Yes. (VPN works fine)

**Viewable on desktop**: Yes but only the first few chapters are accessible on PC/desktop. The rest need the [iOS](https://itunes.apple.com/jp/app/line%E3%83%9E%E3%83%B3%E3%82%AC/id597088068?mt=8)/[Android](https://play.google.com/store/apps/details?id=jp.naver.linemanga.android&hl=ja) app to unlock (can be viewed on PC after unlocked).

(The Japanese seems to go the extra miles to make sure no one can download their images offline T_T. Seems to me their manga sites always impose more limits compared to their Korean/Chinese/English counterparts +__+)

### PR DESCRIPTION
**Pull request by Elastic1**
Resolved #147

### CODE REVIEW

**Review by 27136773 — APPROVED** [review]
Looks good

**Comment by Ever4engel** [comment]
What vpn do you use guys, it's geo blocked
even with proton japanese vpn

**Comment by Elastic1** [comment]
I use PIA.

**Comment by Ever4engel** [comment]
> I use PIA.

need to set language header to jp, That’s why  vpn weren’t working (add to hakuneko internal browser).

**Pull request merged**
