### PR TITLE
mangaokutr

### PR DESCRIPTION
**Pull request by Furkangcmn**
new site  added

### CODE REVIEW

**Review by Sheepux — CHANGES_REQUESTED** [review]
As commented by Ronny : https://github.com/manga-download/hakuneko/pull/5156#issuecomment-1317303688
Please also add an icon for this website

**Comment by MikeZeDev** [comment]
Should i take this over and do it properly instead? 
The submitted file does nothing.

**Comment by Sheepux** [comment]
> Should i take this over and do it properly instead? The submitted file does nothing.

yeah

**Comment by MikeZeDev** [comment]
Closed. This one is the good one https://github.com/manga-download/hakuneko/pull/5298

**Pull request closed without merging**
