### PR TITLE
SaveAsPdf : Fixed reading 'tEXt' chunk for 'png-js' lib

### LINKED ISSUE #5450: [Download as PDF] Maximum Call stack exceeded.
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

**To Reproduce**
1. Name of connector:https://bato.to/
2. Name of manga: The Villainess Turns the Hourglass  (https://bato.to/series/78871/the-villainess-turns-the-hourglass) 
3. Name of chapter 17-10
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
Maximum Call stack exceeded. 

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
image

**HakuNeko (please complete the following information):**
 - Version 6.1.7@554b0c

### PR DESCRIPTION
**Pull request by Druzai**
Continuation of PR #5455
Fixes #5450

### CODE REVIEW

**Comment by MikeZeDev** [comment]
I'll approve this since i've tested it and it works.

**Review by MikeZeDev — APPROVED** [review]

**Comment by 27136773** [comment]
Library code should not be patched, otherwise we have to apply all the changes again whenever the library is updated.
I suggest to directly commit the fix to https://github.com/foliojs/pdfkit instead and then update the library in HakuNeko.

**Comment by Druzai** [comment]
I don't think I can commit the fix to `pdfkit` lib because this error occurs in constructor of `PNG` class. That class is taken from `png-js` lib as a dependency.

I can think of 2 ways to solve the problem:
1. Committing the fix to [pdfkit](https://github.com/foliojs/pdfkit) lib
    - Inherit and extend `PNG` class and change its constructor to fix this problem
    - I don't think it's the right way, because code of `png-js` lib can change. Also it's just duplicating constructor code with 1 small fix... (if there is no other way I will do it)
2. Committing the fix to [png-js](https://github.com/foliojs/png.js) lib
    - Fix constructor of `PNG` class
    - It's more appropriate, but author of that repository has been inactive since 2019 (PRs from 2019 and 2020 haven't been reviewed at all). I think this fix won't be merged.

I think each way is not good enough.

**Comment by Druzai** [comment]
Also the third way was suggested in previous PR as a workaround:
> Another possibility would be try.catch page addition and convert the png only in case of error.

**Comment by MikeZeDev** [comment]
I wanted to submit a PR to pdf-js but like Druzai said judging by folio lack of activity it will most likely never be merged.

On the other hand, it means it probably wont be updated anymore. For that reason i deemed patching the lib an acceptable solution 🤷

**Pull request merged**
