### PR TITLE
Reworked Connector for "onepiece-tube.com"

### PR DESCRIPTION
**Pull request by ProfEibe**
Added feedback from last pullRequest and here is the new version

### CODE REVIEW

**Comment by 27136773** [comment]
References: #3770

**Review by 27136773 — COMMENTED** [review]
Technically good, but not sure about adding a website that only contains a single manga as such websites were rejected before...

**Comment by 27136773** [comment]
If the PR is rejected, you may consider converting to a local plugin:
https://hakuneko.download/docs/install/#user-plugins

**Comment by Sheepux** [comment]
I'd say we have to state : 
* what's the puprpose of this small connector ? 
* Does it provide something not available everywhere else ?

Asking the PR Author's about this.

**Comment by ProfEibe** [comment]
I think I can answer both questions together.
The connected website is the only source I found where there are old and new onepiece chapters translated into german.
Somewhere else there are only the last 5 or something chapters online. So it's purpose is to provide all german translated One Piece chapters.

**Comment by Sheepux** [comment]
Well. let's say ok for once.

**Review by 27136773 — APPROVED** [review]
Looks good, Accepted

**Pull request merged**
