### PR TITLE
Add komiklab & sugarlab

### PR DESCRIPTION
**Pull request by akn19**
* komiklab
* sugarlab

### CODE REVIEW

**Comment by MikeZeDev** [comment]
LGTM. If you can get rid of the useless modification on BakaKomics it would be even better.

**Review by MikeZeDev — CHANGES_REQUESTED** [review]
Get rid of BakaKomik modifications and its good

**Comment by akn19** [comment]
done

**Review by MikeZeDev — APPROVED** [review]

**Comment by 27136773** [comment]
- [Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27komiklab%27&type=code)
- [Missing in HaruNeko](https://github.com/search?q=repo%3Amanga-download%2Fharuneko%20%27sugarlab%27&type=code)

**Pull request merged**
