### PR TITLE
Updated & fixed WeLoMa

### PR DESCRIPTION
**Pull request by onelots**
Fixed WeLoMa (working) #4243 :

-> weloma.net became weloma.art
-> list-manga.html became manga-list.html

### CODE REVIEW

**Comment by onelots** [comment]
don't pay attention to the commits... I can't remember how to do to avoid that X)

**Review by 27136773 — DISMISSED** [review]
Looks good

**Review by 27136773 — COMMENTED** [review]
https://weloma.net/wem still exist, https://weloma.art is probably a different website

**Comment by onelots** [comment]
Hmmm It looks like the same website, nah ? exactly the same theme and the same popular manga, the same recommandations etc 
I think it's the same website behind 2 different domain names

**Comment by Ever4engel** [comment]
the website with .net domain have newer chapters.

**Comment by onelots** [comment]
Yep Ok I'll close this pr so and I'll find a way for WeLoMa.net

**Pull request closed without merging**
